### PR TITLE
fix: don't forward events to workers for completed tasks

### LINKED ISSUE #601: Comment on closed PR can hijack worker
Strange thing that happened to a worker:

Time | Kind | Summary | Task
-- | -- | -- | --
4/9/2026, 8:23:34 PM | webhook | pull_request/opened — #599 "refactor: shared db-client and Task.events static…" | #588
4/9/2026, 8:18:33 PM | message | sent event_notification — issue_comment | #588
4/9/2026, 8:18:33 PM | webhook | issue_comment/created — "**Pattern update** — two refinements to the design since th…" | #588
4/9/2026, 5:24:39 PM | message | sent hello_ack — busy task=#540 | #540
4/9/2026, 5:24:38 PM | message | received worker_hello — busy task=#540 | #540
4/9/2026, 2:20:32 PM | message | sent hello_ack — busy task=#540 | #540
4/9/2026, 2:20:32 PM | message | received worker_hello — busy task=#540 | #540
4/9/2026, 2:16:48 PM | message | sent task_assigned | #540
4/9/2026, 1:54:14 PM | message | sent hello_ack — idle | —
4/9/2026, 1:54:14 PM | message | received worker_hello — idle | —
4/9/2026, 1:11:42 PM | message | disconnected (code 1006) | —
4/9/2026, 12:39:02 PM | message | received task_complete | #588

Basically, it completed a task, then got assigned a new one. While it was working on the new one, a comment was added to the task it had previously completed. That comment got forwarded to the worker. The worker decided it was supposed to be working on what the comment talked about, and so it checked out the old branch and started new work.

Events on an issue/PR should not be forwarded to a worker after the task is complete. And the worker should probably ignore them if they do arrive, when it is working on a different task.

### PR DESCRIPTION
**Pull request by jasoncrawford**
## Summary

Fixes the bug where a comment on a completed issue was forwarded to the worker now assigned to a different task, causing the worker to check out the old branch and start new work.

Two-part fix:

- **Foreman (`forwardEvent`)**: Add a guard that drops events when `task.status` is `complete`, `closed`, or `merged`. Previously, `forwardEvent` checked `task.workerId` before checking task status. Since `task.complete()` sets `completedAt` but does NOT clear `workerId`, a completed task still passes the `if (task.workerId)` check and events were forwarded to the former worker — which may now be busy on a different task.

- **Worker (`handleMessage`)**: Add a `taskId` guard in the `event_notification` handler that ignores events for tasks other than `this.currentTaskId`. This is a defensive second layer: even if a stale event somehow arrives (e.g. from a race or foreman bug), the worker won't act on it.

## Test plan

- [x] New test file `foreman.event-router.test.ts` with direct unit tests for `forwardEvent` covering complete/closed/merged tasks
- [x] New tests in `worker.test.ts` verifying the worker ignores `event_notification` for a different `taskId` and prints a warning
- [x] Updated existing test that sent `event_notification` without a prior `task_assigned` (that was always a latent bug — events for an idle worker with no task should be ignored)
- [x] All 1318 non-DB tests pass; DB tests require Supabase

Closes #601

### CODE REVIEW

File: src/agent/worker.ts [hunk 1]
```diff
@@ -594,6 +594,12 @@ export class WorkerSession {
       this.display.print(display.c.sageGreen(initialPrompt));
       void this.runQueryLoop(initialPrompt);
     } else if (msg.type === "event_notification") {
+      // Ignore stale events forwarded for tasks we're no longer working on.
+      if (msg.taskId !== this.currentTaskId) {
+        this.display.print(display.c.amber(`[worker] ignoring event_notification for task ${msg.taskId} (current: ${this.currentTaskId ?? "none"})`));
```
Comment (jasoncrawford) [inline src/agent/worker.ts]: doesn't need to be amber… dark grey

File: src/foreman/controllers/event-router.ts [hunk 2]
```diff
@@ -94,6 +94,13 @@ export function isMutedEvent(name: string): boolean {
 // ── Event forwarding ─────────────────────────────────────────────────────────
 
 export function forwardEvent(deps: EventRouterDeps, task: Task, evt: GitHubEvent, ref: string): void {
+  // Never forward events for tasks that are no longer active.
+  const { status } = task;
+  if (status === "complete" || status === "closed" || status === "merged") {
```
Comment (jasoncrawford) [inline src/foreman/controllers/event-router.ts]: Wait, let's still forward events for closed and merged tasks. Until it's complete, the worker is still focused on that task, even if the PR is merged or the issue is closed. Only stop forwarding on completion.

**Review by jasoncrawford — COMMENTED** [review]
Good catches, both addressed:

- **Forwarding for closed/merged**: narrowed the guard to `complete` only. Closed and merged tasks still forward events to the worker.
- **Color**: changed the ignore warning to `display.c.darkGray`.

File: src/foreman/controllers/event-router.ts [hunk 3]
```diff
@@ -94,6 +94,13 @@ export function isMutedEvent(name: string): boolean {
 // ── Event forwarding ─────────────────────────────────────────────────────────
 
 export function forwardEvent(deps: EventRouterDeps, task: Task, evt: GitHubEvent, ref: string): void {
+  // Never forward events for tasks that are no longer active.
+  const { status } = task;
+  if (status === "complete") {
+    deps.flog(`[task ${ref}] ${evt.name} dropped — task is ${status}`);
+    return;
+  }
+
```
Comment (jasoncrawford) [inline src/foreman/controllers/event-router.ts]: Actually, I wonder if a cleaner fix is: instead of checking task status, do the following: once we look up the worker, check what its current task is. If it's not this task, then drop. That mirrors the worker-side logic.

**Review by jasoncrawford — COMMENTED** [review]
Good call. The registry already has `currentTaskId` on each `WorkerState`, and `releaseWorker()` (called on `task_complete`) clears it — so after completion, `worker.currentTaskId` is either `undefined` or a new task ID, and either way the guard fires. Switched to that approach: checks `worker && worker.currentTaskId !== task.taskId` before the disconnected/connected branches, dropping the event if the worker has moved on. Removed the task-status check entirely.
